### ISSUE TITLE
Добавить таргетирование карты яндекса по введенному адресу

### ISSUE THREAD

**Issue by SchamanGrin** [aisenpopov/strela#8]
При заполнении нового зала, карта яндекса не реагирует на указание адреса. Точку приходится ставить вручную. Если для Москвы я еще справляюь, то по остальным городам может быть проблема. @isnpops

**Comment by aisenpopov** [comment]
Написал в техподдержку яндекса. Жду ответа.

**Comment by aisenpopov** [comment]
Поправил. Надо писать адрес в поисковое поле, которое показывается на самой карте.
